### DISCUSSION TITLE
Pod metric not being read

### DISCUSSION THREAD

**Discussion by vobrien-axway** [jthomperoo/custom-pod-autoscaler#192] [Q&A] [answered]
I have updated my config with the following kuberenetesMetricSpec:

```
kubernetesMetricSpecs:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
  - type: Pods
    pods:
      metric:
        name: kube_pod_info
      target:
        type: AverageValue
requireKubernetesMetrics: true
runMode: "per-pod"
```
Within the returned data I see both the memory and cpu resource kubernetesMetrics fields, but that is it, the 3rd Pods field doesn't show up at all. I have tried both with runMode set to: per-pod and per-resource.

If I configure a HPA with the same values, all show up and are providing data.

I assume I just have something misconfigured but can't figure out what and I don't see any errors.

Any suggestions
