### ISSUE TITLE
[Question] Logging in examples 

### ISSUE THREAD

**Issue by prayagsingh** [jthomperoo/custom-pod-autoscaler#139]
I'm going through this [example](https://github.com/jthomperoo/custom-pod-autoscaler/tree/master/example/simple-pod-metrics-golang) and I have added some checks(`log.Print`) for printing the values to understand this example much better. But I'm not getting these logs when I'm executing the `kubectl logs` command. 

It would be a great help if you can please suggest how can I get/merge these logs with the `kubectl logs` command.

**Comment by jthomperoo** [comment]
Hmm, so if the execution is successful (`exit status 1`) then anything printed to stderr will be discarded and will not be logged. I think this is a valid concern for logging though, would you be interested in a feature that would include anything printed out to stderr to be printed out to the CPA logs (so you could access it with `kubectl logs`)? Perhaps maybe a configuration option included in the `shell` method that would be like:

```yaml
evaluate:
  type: "shell"
  timeout: 2500
  shell: 
    entrypoint: "/bin/sh"
    logStderr: true
    command: 
      - "-c"
      - "/simple-pod-metrics-golang -mode=evaluate"
```

I think this might be a nice feature to add to help debugging.
