### ISSUE TITLE
plural for resource always adds "s"

### ISSUE THREAD

**Issue by martin-ilavsky** [jthomperoo/custom-pod-autoscaler#199]
**Describe the bug**

`kindPlural := fmt.Sprintf("%ss", strings.ToLower(kind))`
This always adds 's' to kind. But in case of CRD resource like logstash, the plural is logstashes and not logstashs. This is causing it to fail

**To Reproduce**
1. Deploy logstash CRD
2. Use scaleTargetRef  as '{"kind": "Logstash", "name": "logstash", "apiVersion": "logstash.k8s.elastic.co/v1alpha1"}'
3. See error

**Expected behavior**
find correct resource

**Kubernetes Details (`kubectl version`):**
1.32

**Comment by jthomperoo** [comment]
Thanks for raising this - I always knew this was a bit of a hack when it was first implemented but it seemed to work for the use cases I could think of; I'll investigate the correct way of getting the plural kind.

**Comment by martin-ilavsky** [comment]
Please also note that you are trying to patch replicas

```
// Prepare patch
patch := []byte(fmt.Sprintf(`{"spec":{"replicas":%d}}`, targetReplicas))
```

But CRDs have section where its specifically defined how to scale them. For example Logstash CRD.
```
subresources:
  scale:
    labelSelectorPath: .status.selector
    specReplicasPath: .spec.count
    statusReplicasPath: .status.expectedNodes 
```

It defines how to scale replicas, get current replicas count and selector

**Comment by jthomperoo** [comment]
Dug into this a bit more and got it reading the CRD and using the specified `specReplicasPath` for applying the patch, however I think I'm hitting this issue: https://github.com/kubernetes/kubernetes/issues/116311

Not 100% sure on that yet, but going to see what I can do to get around this.

**Comment by martin-ilavsky** [comment]
I hit that as well, i have dida dirty workaround and used curl to call the k8s API

**Comment by jthomperoo** [comment]
OK did some more playing around with this, I now think we don't need to do anything special with the `subresource.scale.specReplicasPath` - I don't think this is designed for us to account for, instead these are instructions for the Scale API.

Here's my test logstash resource called `quickstart` (omitted some fields to make it easier to read):

```bash
kubectl get logstashes quickstart -o=yaml
```

```yaml
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: quickstart
  namespace: default
spec:
  config:
    log.level: debug
    pipeline.workers: 4
  count: 1
  elasticsearchRefs:
  - clusterName: qs
    name: quickstart
  version: 8.17.2
status:
  elasticsearchAssociationsStatus:
    default/quickstart: Pending
  observedGeneration: 1
  selector: ""
```

Here the `count ` is 1.

Here's the scale subresource:

```bash
kubectl get logstashes quickstart --subresource scale -o=yaml
```

```yaml
apiVersion: autoscaling/v1
kind: Scale
metadata:
  name: quickstart
  namespace: default
spec:
  replicas: 1
status:
  replicas: 0
```

If I then patch the scale sub-resource, modifying the `spec.replicas` field, it will then apply these changes to the logstash resource automatically for me.

```bash
kubectl patch logstashes quickstart --subresource='scale' --type='json' -p '[{"op":"replace","path":"/spec/replicas","value":5}]'
```

Automatically updated logstash resource (see the `count` field has been updated):

```yaml
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: quickstart
  namespace: default
spec:
  config:
    log.level: debug
    pipeline.workers: 4
  count: 5
  elasticsearchRefs:
  - clusterName: qs
    name: quickstart
  version: 8.17.2
status:
  elasticsearchAssociationsStatus:
    default/quickstart: Pending
  observedGeneration: 2
  selector: ""
```

And my scale sub-resource:

```yaml
apiVersion: autoscaling/v1
kind: Scale
metadata:
  creationTimestamp: "2025-02-14T10:26:04Z"
  name: quickstart
  namespace: default
  resourceVersion: "1233"
  uid: a521df84-98f3-4a26-a036-911c60ed2f12
spec:
  replicas: 5
status:
  replicas: 0
```

This is much easier, as the CPO does not need to query any CRDs then and handle things specially (it also means we don't need to set up a cluster role to be able to do that). I think we can just patch that replicas field.

I've almost got these changes done to correctly get the plural form, just need to get the unit tests fixed and do a bit of testing then should be good to go.
