### ISSUE TITLE
Allow different methods to pass data

### ISSUE THREAD

**Issue by jthomperoo** [jthomperoo/custom-pod-autoscaler#75]
Would require a change to how the current configuration to support this, e.g. instead of
```yaml
metric: "shell command"
```
It should allow you to specify which way to pass data, for shell commands:
```yaml
metric: 
  type: "pipe"
  pipe: "shell command"
```
For something like a HTTP request:
```yaml
metric: 
  type: "http"
  http: 
    method: "GET"
    endpoint: "https://0.0.0.0:5000/metrics"
```
This would also apply to evaluations, so a more general configuration option to specify a series of different data transfer options would be useful.
