### ISSUE TITLE
Support data transfer using HTTP, allowing passing data either as a query param or request body

### ISSUE THREAD

**Issue by jthomperoo** [jthomperoo/custom-pod-autoscaler#76]
Relies on #75 
For something like a HTTP request:
```yaml
metric: 
  type: "http"
  http: 
    method: "GET"
    headers: 
      - key: value
      - key: value
    url: "https://0.0.0.0:5000/metrics"
    parameterMethod: query
```
